{% set name = "pairtools" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cded88f07dbc7b829bfb2e1979755f81b3777b85371363d70ba185df7c609f6b

build:
  number: 1
  skip: True # [py<35]
  entry_points:
    - pairtools = pairtools:cli

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cython

  run:
    - python
    - coreutils
    - numpy
    - click
    - lz4-c
    - samtools
    - tabix
    - pbgzip

test:
  imports:
    - pairtools

  commands:
    # click requires a unicode locale
    - pairtools --help

about:
  home: https://github.com/mirnylab/pairtools
  license: MIT
  license_family: MIT
  summary: 'CLI tools to process mapped Hi-C data'
  license_file: LICENSE.txt
  doc_url: http://pairtools.readthedocs.io/
  dev_url: https://github.com/simplejson/simplejson


extra:
  container:
    # click requires a unicode locale when used with Python 3
    # extended-base generates en_US.UTF-8 locale and sets LC_ALL, LANG properly
    extended-base: true  # [py3k]
    recipe-maintainers:
      - golobor
