{% set name = "BBMap" %}
{% set version = "38.18" %}
{% set sha256 = "ab41a6b27c6bf884c8d509d97b8619c79715443fb3d76e6b451f5430ce7d4aa6" %}

about:
  home: 'https://sourceforge.net/projects/bbmap'
  license: "UC-LBL license (see package)"
  summary: "BBMap is a short read aligner, as well as various other bioinformatic tools."

build:
  number: 0
  noarch: generic

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  sha256: {{ sha256 }}
  url: http://downloads.sourceforge.net/project/{{ name|lower }}/{{ name }}_{{ version }}.tar.gz

requirements:
  build:
    - openjdk >=7.0
  run:
    - openjdk >=7.0

test:
  commands:
    - bbmap.sh -V 2>&1 | grep "BBMap" > /dev/null
    - bbmap.sh -V 2>&1 | grep "Version {{ version }}" > /dev/null
    - bbmerge.sh -V 2>&1 | grep "BBMerge" > /dev/null
    - bbduk.sh -V 2>&1 | grep "BBDuk" > /dev/null
    - bbmask.sh -V 2>&1 | grep "BBMask" > /dev/null
    - bbnorm.sh --help 2>&1 | grep "BBNorm" > /dev/null

extra:
  notes: |
    BBMap is a series of Java programs, but they come with a number of custom
    wrapper shell scripts. Each of these is symlinked to the conda bin directory
    during install.
  identifiers:
    - biotools:bbmap
