{% set name = "primer3" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 1

source:
  url: https://github.com/primer3-org/primer3/archive/v2.4.0.tar.gz
  md5: aed6546bdfb60652cd7eba8d51eae8cc
  # makefile.patch is taken from the biobuilds channel
  patches:
    - makefile.patch

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - perl
  run:
    - perl

test:
  commands:
    - primer3_core --help 2>&1 | grep 'This is primer3'

about:
  home: https://github.com/primer3-org/primer3
  license: GPLv2
  license_file: LICENSE
  summary: 'Design PCR primers from DNA sequence. From mispriming libraries to sequence quality data to the generation of internal oligos, primer3 does it.'

extra:
  identifiers:
    - biotools:primer3
    - doi:10.1093/nar/gks596
