{% set name = "plasflow" %}
{% set version = "1.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 352d5d7cd73672130e32f3f61c3f2ad95aa684d7aebf7668ab3f2594996c338b

build:
  number: 0
  skip: True # [not py35 or osx]

requirements:
  host:
    - biopython
    - numpy
    - pandas
    - pip
    - rpy2 >=2.8
    - scikit-learn =0.18.1
    - scipy
    - bioconductor-biostrings
    - tensorflow =0.10.0
  run:
    - biopython
    - numpy
    - pandas
    - rpy2 >=2.8
    - scikit-learn =0.18.1
    - scipy
    - bioconductor-biostrings
    - tensorflow =0.10.0
test:
  imports:
    - plasflow
  commands:
    - PlasFlow.py --help

about:
  home: https://github.com/smaegol/PlasFlow
  license: GNU General Public v3 or later (GPLv3+)
  license_family: GPL3
  summary: PlasFlow - predicting plasmid sequences in metagenomic data

