{% set name = "plasflow" %}
{% set version = "1.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 352d5d7cd73672130e32f3f61c3f2ad95aa684d7aebf7668ab3f2594996c338b

build:
  number: 0
  #script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - biopython
    - numpy
    - pandas
    - pip
    - rpy2
    - scikit-learn
    - scipy
    - bioconductor-biostrings
    - tensorflow
    - python
  run:
    - biopython
    - numpy
    - pandas
    - rpy2
    - scikit-learn
    - scipy
    - bioconductor-biostrings
    - tensorflow
    - python
test:
  imports:
    - plasflow

about:
  home: https://github.com/smaegol/PlasFlow
  license: GNU General Public v3 or later (GPLv3+)
  license_family: GPL3
  summary: PlasFlow - predicting plasmid sequences in metagenomic data

