c_compiler:
  - gcc ==4.8.5 # [linux]
  - llvm # [osx]
  #- gcc      # [linux]
  #- clang    # [osx]
cxx_compiler:
  - gcc ==4.8.5 # [linux]
  - llvm # [osx]
  #- gxx      # [linux]
  #- clangxx  # [osx]
  
  
